import numpy as np
import matplotlib.pyplot as plt
x=np.arange(-5,6)
y=x*x
plt.plot(x,y)
plt.title("square")
plt.show()

plt.style.use('dark_background')
x=np.arange(-2*np.pi,2*np.pi,0.1)
plt.figure(figsize=(10,8))
y=np.sin(x)
plt.subplot(2,2,1)
plt.plot(x,y,'r')
plt.title("SIN GRAPH")
y=np.cos(x)
plt.subplot(2,2,2)
plt.plot(x,y,'b')
plt.title("COS GRAPH")
y=np.tan(x)
plt.subplot(2,2,3)
plt.plot(x,y,'g')
plt.title("TAN GRAPH")
plt.ylim(-10, 10)
y=1/(np.tan(x))
plt.subplot(2,2,4)
plt.plot(x,y,'')
plt.title("COT GRAPH")
plt.ylim(-10, 10)
plt.show()
