import pandas as pd
import numpy as np
lst=np.arange(1,49).reshape(4,12)
#series=pd.Series(lst,index=[10,20,30,40,50])
#dic={'p': 1,'q': 2,'r': 3,'s': 4,'t': 5}
#dic=pd.Series(dic,name='alphabet')
#print(dic)
#df=pd.DataFrame(lst)
df=pd.read_csv(r'C:\Users\moury\OneDrive\Desktop\Sun Breathing\ML\test.csv',encoding='utf-8')
#print(df.columns)
#print(df.shape)
#print(df.size)
#print(df.head())
#print(df.tail())
#print(df.head(2))
#print(df.describe())
c=df.isnull()
c=df.isnull().sum()
df2=df.dropna()
#df2=df.dropna(axis=1)
#df2=df.dropna(how='any')
#df2=df.fillna({'Name': 'user','Age': df['Age'].mean()})
df2=df['Name'].fillna('User')
print(df)
print(df2)